@{
    ModuleVersion = '1.0.0'
    RootModule    = 'HermesHomeServer.psm1'
    GUID          = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'
    Author        = 'Hermes Home Server'
    Description   = 'Модули установки и обслуживания Hermes Home Server на Windows 11'
    FunctionsToExport = @(
        'Get-HermesProjectRoot'
        'Write-HermesStep'
        'Write-HermesTextFile'
        'Test-DockerInstalled'
        'Test-DockerRunning'
        'Ensure-Docker'
        'Get-HermesEnv'
        'Set-HermesEnv'
        'Get-DefaultModelForProvider'
        'Get-ProviderDisplayName'
        'New-HermesConfig'
        'Test-HermesConfigured'
        'Ensure-HermesDataDirs'
        'Ensure-Hermes'
        'Test-HermesHealthy'
        'Test-TelegramConfigured'
        'Get-HermesStatus'
        'Send-TelegramMessage'
        'New-HermesBackup'
        'Get-HermesBackups'
        'Restore-HermesBackup'
        'Ensure-TelegramBackupCommands'
        'Ensure-BackupSchedule'
        'Remove-BackupSchedule'
        'Ensure-WatchdogSchedule'
        'Remove-WatchdogSchedule'
        'Ensure-ModelCheckSchedule'
        'Remove-ModelCheckSchedule'
        'Ensure-ServerPower'
        'Update-Hermes'
        'Uninstall-HermesHome'
    )
}
